### ISSUE TITLE
Idea about dependencies

### ISSUE THREAD

**Issue by mahnunchik** [icflorescu/aspa#1]
Maybe it would be a good idea to move the non-core dependencies to devDependencies?
I mind _csso_, _jade_, _stylus_ etc

**Comment by icflorescu** [comment]
Hi Eugeny,

Thanks for your suggestion. I'll think about it, although it's difficult to decide which are the core vs. non-core dependencies; i.e. some people are taking **jade** for granted when writing Express apps. I don't know, maybe it would make sense to only `require` csso and uglify-js when building for production... 

Plus, ASPA is intended as a "generator" tool to be used during **development**, and one of its main purposes is to help us get rid of those unnecessary dependencies **in production** and that's precisely why I've built [ASPA-Express](https://github.com/icflorescu/aspa-express) dependency-free.

In other words, if you use ASPA during development (or as a deployment step) to process your assets and the [ASPA-Express](https://github.com/icflorescu/aspa-express) middleware, your web app won't depend on **csso**, **jade**, **stylus**, **coffee-script**, etc.

I'm actually using ASPA and ASPA-Express in a mapping project right now; I'm using stylus, writing the client-side code in IcedCofeeScript and I'm also using Jade templates **in the browser**... all these are continuosly translated to pure CSS & JavaScript during development (with `aspa -r ../webapp watch`). Before deploying on my test environment on Heroku I do something like `aspa -r ../webapp build -m production` and everything gets properly minified and fingerprinted, and the webapp slug size is under 10 MB...  

If you have any more suggestions about this, please feel free to comment/ask and I'll try to answer asap.

Thanks again!
